name: FTSKampf
version: '2.1.0'
main: de.ftscraft.ftskampf.main.FTSKampf
api-version: '1.20'
depend:
  - FTSEngine
authors: [ Melleming, CiraThomasen ]
commands:
  kampf:
  hp:
  heilen:
  kampfskill:
  hurt:
  react:
  magie:
  ftskampfdb:
