name: FTSKampf
version: ${project.version}
main: de.ftscraft.ftskampf.main.FTSKampf
api-version: '1.20'
depend:
  - FTSEngine
author: Melleming
commands:
  kampf:
  hp:
  heilen:
  kampfskill:
  hurt:
  react:
  magie:
  ftskampfdb:
  setpoints:
